project:
  type: r3-theme
  # pre-render: bash _build-slides.sh
  # resources:
  #   - slides/*.html

book:
  title: Intro R Package Development
  subtitle: An introductory course on building R packages
  description: A 3-day course for researchers that introduces how to build an R package that they and their colleagues can install and use.
  author:
    - name: Luke W. Johnston
      orcid: 0000-0003-4169-2616
      corresponding: true
    - name: Signe Kirk Brødbæk
    - name: Roger Moreno Justicia
    - name: Anders Askeland
    - name: Anders Aasted Isaksen
    - name: Omar Silverman
  date: last-modified
  repo-url: https://github.com/rostools/r-pkg-intro
  site-url: https://r-pkg-intro.rostools.org
  chapters:
    - index.qmd
    - part: "Preamble"
      chapters:
      - preamble/syllabus.qmd
      - preamble/schedule.qmd
      - preamble/pre-course.qmd
    - part: "Sessions"
      chapters:
      - sessions/introduction.qmd
      - sessions/package-setup.qmd
      - sessions/function-development.qmd
      - sessions/documenting-functions.qmd
      - sessions/testing.qmd
      - sessions/debugging.qmd
      - sessions/automated-testing.qmd
      - sessions/writing-guides.qmd
      - sessions/creating-website.qmd
      - sessions/what-next.qmd
  appendices:
    - appendix/project.qmd
    - appendix/social.qmd
    - appendix/for-instructors.qmd
    - appendix/references.qmd
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.html
      - text: "Code of Conduct"
        href: "https://guides.rostools.org/conduct.html"

format:
  r3-theme-html:
    include-before-body:
      - includes/contribute.html
      # TODO: Add Goat counter.

editor:
  markdown:
    wrap: 72
    canonical: true
