project:
  type: r3-theme
  # pre-render: bash _build-slides.sh
  # resources:
  #   - slides/*.html

book:
  title: Testing
  author: Luke W. Johnston
  date: last-modified
  repo-url: https://github.com/rostools/r-cubed
  chapters:
    - index.qmd
    - part: "Preamble"
      chapters:
      - preamble/syllabus.qmd
      - preamble/schedule.qmd
      - preamble/pre-course.qmd
    - part: "Sessions"
      chapters:
      - sessions/introduction.qmd
      - sessions/lesson.qmd
      - sessions/what-next.qmd
  appendices:
    - appendix/social.qmd
    - appendix/for-instructors.qmd
    - appendix/references.qmd
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.html
      - text: "Code of Conduct"
        href: "https://guides.rostools.org/conduct.html"

format:
  r3-theme-html: default

editor:
  markdown:
    wrap: 72
    canonical: true
