---
format: r3-theme-revealjs
search: false
---

# Welcome to the TODO: add course name

-   :heavy_check_mark: Accept the GitHub Organization invite
-   :heavy_check_mark: Accept the Slack channel invite
-   :heavy_check_mark: Go to the table with the group name
-   :heavy_check_mark: Introduce yourself to your group members

::: notes
Introduce instructors and helpers after welcoming everyone and getting
them to do this.
:::

## :raising_hand_woman: Before this course... How many knew or have heard about ... {.center}

::: notes
Raise your hands.
:::

# TODO: Section for general introduction

## Scientific culture is not well-prepared for analytic and computation era {.center}

## These issues can be fixed by creating and nurturing a culture of openness {.center}

::: notes
All of this is because of a problem with our culture in research. We
aren't open, we don't really share, and don't often follow basic
principles of science. To fix this, we need to start creating and
nurturing a better and healthier culture. We all can be involved in
that, we all have that power to do something, even if its small thing.
:::

## Goal of this course: Start changing the culture by providing the training {.center}

# Course details

## Setup and layout {.smaller}

::: columns
::: {.column width="50%"}
-   Course is mix of:
    -   "Code-alongs" (we type and explain, you type along)
    -   Hands-on coding, discussing, and reading exercises
    -   Group project (quickly go over it)
-   All material is online (and [openly licensed](../LICENSE.html))
-   [Further Learning](https://guides.rostools.org/learning.html) page
    for resources
:::

::: {.column width="50%"}
-   Reading tasks are "callout" blocks marked by the blue line on the
    left side of the text
-   Schedule listed is a *guide* only, some sessions are longer, others
    shorter
-   Less about coding, more about connecting with others
    -   During lunch, try to sit beside someone you don't know
    -   Several networking activities (usually after lunch)
:::
:::

::: notes
Explain a bit more about the reading, why doing it, and that this course
in particular has a lot more of it than more advanced courses.
:::

## Getting or asking for help :raising_hand_woman::raising_hand_man: {.smaller}

-   Put the sticky on your laptop to get help
-   There are lots of helpers
-   Team members, try to help out too
-   We're all learning here!
    -   This is a supportive and safe environment
    -   Remember our [Code of Conduct](conduct.html)

## Practice using stickies: Have you TODO: Complete this. {.center}

# Activities {.center}

## :walking::walking_woman: Who has TODO: Complete this {.center}

::: notes
Go to different sides of the room for "Yes" and "No". Or a continuum
from one end of the room to the other.
:::
