# Schedule {#sec-schedule}

{{< include ../includes/_wip.qmd >}}

The course is structured as a series of participatory live-coding
sessions interspersed with hands-on exercises and group work, using
either a practice dataset or some other real-world dataset. There are
some lectures given, mainly at the start and end of the course. The
general schedule outline is shown in the below table. This is not a
fixed schedule of the timings of each session --- some may be shorter
and others may be longer. Instead, it is meant to be an approximate
guide and overview.

::: panel-tabset
## Day 1 {.unnumbered}

| Time | Session topic |
|:------------|:----------------------------------------------------------|
| 9:30 | {{< fa mug-hot >}} Arrival. Coffee and snacks |
| 10:00 | {{< fa person-chalkboard >}} [Introduction to the course](../sessions/introduction.qmd) |
| 10:30 | {{< fa laptop-code >}} [Package setup](../sessions/package-setup.qmd) |
| 12:30 | {{< fa utensils >}} Lunch |
| 13:15 | {{< fa user-group >}} [Networking and social activity](../appendix/social.qmd#social-day-one) |
| 13:35 | {{< fa laptop-code >}} [Package setup](../sessions/package-setup.qmd) |
| 14:45 | {{< fa mug-hot >}} Break with coffee and snacks |
| 15:00 | {{< fa laptop-code >}} [Function development in a package environment](../sessions/function-development.qmd) |
| 16:30 | {{< fa comment-dots >}} End-of-day short survey |

## Day 2 {.unnumbered}

| Time | Session topic |
|:------------|:----------------------------------------------------------|
| 9:00 | {{< fa laptop-code >}} [Documenting functions](../sessions/documenting-functions.qmd) |
| 10:15 | {{< fa mug-hot >}} Break with coffee, tea, and snacks |
| 10:30 | {{< fa laptop-code >}} [Creating formal tests of functions](../sessions/testing.qmd) |
| 12:30 | {{< fa utensils >}} Lunch |
| 13:15 | {{< fa user-group >}} [Networking and social activity](../appendix/social.qmd#social-day-two) |
| 13:35 | {{< fa laptop-code >}} [Debugging issues in your functions](../sessions/debugging.qmd) |
| 14:45 | {{< fa mug-hot >}} Break with coffee and snacks |
| 15:00 | {{< fa laptop-code >}} [Automated and independent testing](../sessions/automated-testing.qmd) |
| 16:30 | {{< fa comment-dots >}} End-of-day short survey |

## Day 3 {.unnumbered}

| Time | Session topic |
|:------------|:----------------------------------------------------------|
| 9:00 | {{< fa laptop-code >}} [Writing usage and guide documents](../sessions/writing-guides.qmd) |
| 10:15 | {{< fa mug-hot >}} Break with coffee and snacks |
| 11:00 | {{< fa laptop-code >}} [Creating a package website](../sessions/creating-website.qmd) |
| 12:30 | {{< fa utensils >}} Lunch |
| 13:15 | {{< fa user-group >}} [Project work](../appendix/project.qmd) |
| 16:00 | {{< fa person-chalkboard >}} [Closing remarks](../sessions/what-next.qmd) |
| 16:30 | {{< fa comment-dots >}} End-of-course short survey and farewell |
:::